name: RawDrop
options:
  bundleIdPrefix: com.akakika
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  developmentLanguage: en
settings:
  base:
    SWIFT_VERSION: "5.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_ALLOWED: "YES"
    CODE_SIGNING_REQUIRED: "NO"
targets:
  RawDrop:
    type: application
    platform: macOS
    sources:
      - path: RawDrop
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.akakika.RawDrop
        PRODUCT_NAME: RawDrop
        INFOPLIST_FILE: RawDrop/Info.plist
        GENERATE_INFOPLIST_FILE: false
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: true
        COMBINE_HIDPI_IMAGES: true
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        MARKETING_VERSION: "0.3.8"
        CURRENT_PROJECT_VERSION: "8"
    entitlements:
      path: RawDrop/RawDrop.entitlements
